### ISSUE TITLE
Rstar tests failing

### ISSUE THREAD

**Issue by sethaxen** [TuringLang/MCMCDiagnosticTools.jl#56]
The `rstar` tests now fail on main, while 3 weeks ago they passed.

Since none of the MLJ packages have new versions in that period, I suspect the issue is either with the update from XGBoost.jl v2.1.0 to v2.2.0 (see https://github.com/TuringLang/MCMCDiagnosticTools.jl/actions/runs/3698624468/jobs/6265059551#step:6:152 vs https://github.com/TuringLang/MCMCDiagnosticTools.jl/actions/runs/3830047637/jobs/6517430737#step:6:164) or with the update from XGBoost_jll v1.7.1+0 to v1.7.2+0.

The main change to XGBoost.jl may be https://github.com/dmlc/XGBoost.jl/pull/142

**Comment by devmotion** [comment]
I have been annoyed by XGBoost.jl for a while - it broke our tests multiple times in the last few months and always required workarounds for older Julia versions and 32bit (which is not supported but was not stated officially when we ran into some issues). I also don't understand why it is necessary to add a dependency on CUDA for all downstream packages and users... Hopefully they'll make it a weak dependency rather sooner than later.

If it would not be so popular among users (I assume) I would have suggested removing it from our tests a long time ago.

I wonder if we can put together a MWE and open an issue upstream.

**Comment by sethaxen** [comment]
> I have been annoyed by XGBoost.jl for a while - it broke our tests multiple times in the last few months and always required workarounds for older Julia versions and 32bit (which is not supported but was not stated officially when we ran into some issues). I also don't understand why it is necessary to add a dependency on CUDA for all downstream packages and users... Hopefully they'll make it a weak dependency rather sooner than later.

Yeah, and it has a number of maintenance issues as well (like no GitHub releases and apparently some permissions issues for the maintainers). I like the idea in #57 of moving away from XGBoost.

> I wonder if we can put together a MWE and open an issue upstream.

I've confirmed locally that if we pin XGBoost to v2.1.0 the tests pass, while if we update to v2.1.1 the tests fail, regardless of the XGBoost_jll version or the Julia version (v1.8.3 vs v1.8.4). I'll try to put together an MWE.

**Comment by sethaxen** [comment]
This seems to have been fixed everywhere but on windows. This seems to coincide with XGBoost_jll.jl being updated to v1.7.3. This makes me think the issue was a bug introduced in xgboost itself, which was fixed in https://github.com/dmlc/xgboost/releases/tag/v1.7.3

I wonder why our windows CI is so non-informative when it fails, not even showing which tests fail and why.

**Comment by devmotion** [comment]
The Windows issue is a Julia bug: https://github.com/JuliaLang/julia/issues/48187 (unfortunately not fixed on Julia 1.8.5, it seems)

**Comment by sethaxen** [comment]
Doctests are now failing, it seems thanks to https://github.com/dmlc/XGBoost.jl/pull/159

**Comment by devmotion** [comment]
I think the problem is that in MLJXGBoostInterface the list of parameters is too long: https://github.com/dmlc/XGBoost.jl/pull/159#issuecomment-1382459040
